### ISSUE TITLE
After redeploy csi-s3-test-nginx pod occur `Transport endpoint is not connected`

### ISSUE THREAD

**Issue by dyrnq** [yandex-cloud/k8s-csi-s3#106]
Steps to reproduce

1. deploy k8s-cis-s3
2. create sc
```
cat <<EOF | kubectl apply -f -
# Source: csi-s3/templates/storageclass.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-s3
provisioner: ru.yandex.s3.csi
parameters:
  mounter: "geesefs"
  options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  csi.storage.k8s.io/provisioner-secret-name: csi-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
reclaimPolicy: Delete
EOF
```
3. deploy example pvc and pod
```bash
cat <<EOF | kubectl apply -f -
# https://github.com/yandex-cloud/k8s-csi-s3/blob/master/deploy/kubernetes/examples/pvc.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-s3
# https://github.com/yandex-cloud/k8s-csi-s3/blob/master/deploy/kubernetes/examples/pod.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-nginx
  namespace: default
spec:
  containers:
   - name: csi-s3-test-nginx
     image: nginx
     volumeMounts:
       - mountPath: /usr/share/nginx/html/s3
         name: webroot
  volumes:
   - name: webroot
     persistentVolumeClaim:
       claimName: csi-s3-pvc
       readOnly: false
EOF
```
```bash
kubectl exec -it pod/csi-s3-test-nginx -- bash -c "echo hello >> /usr/share/nginx/html/s3/index.html"
kubectl exec -it pod/csi-s3-test-nginx -- bash -c "curl http://127.0.0.1/s3/index.html"

systemctl list-units --no-pager |grep gee
  geesefs-pvc_2d7451f1a3_2ddcd1_2d4c08_2db57b_2dc146a8b66105.service                                                                                                     loaded active running   GeeseFS mount for Kubernetes volume pvc-7451f1a3-dcd1-4c08-b57b-c146a8b66105


```
4. delete csi-s3-test-nginx pod
```bash
kubectl delete pod csi-s3-test-nginx
```
5. redo step3
6. occur `Transport endpoint is not connected`
```bash
kubectl exec -it pod/csi-s3-test-nginx -- bash -c "ls -l /usr/share/nginx/html/s3"
ls: cannot access '/usr/share/nginx/html/s3': Transport endpoint is not connected
command terminated with exit code 2
```

I'm not sure if this is a problem, Could you please help confirm this? TKS.
