### ISSUE TITLE
can not mount with non exist directory

### ISSUE THREAD

**Issue by chinhtrandn** [yandex-cloud/k8s-csi-s3#113]
Hi
I can not mount with non exist directory
 ```
containers:
    - name: nginx
      image: nginx:latest      
      ports:
        - containerPort: 8080
      imagePullPolicy: 
      volumeMounts:
        - name: home
          mountPath: /abcdef      
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "4000m"
          memory: "16Gi"
          nvidia.com/gpu: 0 
  volumes:
    - name: home     
      persistentVolumeClaim:
        claimName: csi-s3-pvc
        readOnly: false
```
Result

> MountVolume.SetUp failed for volume "hh-test" : rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/ru.yandex.s3.csi/52068b87812173cb32c3970886e82aeb7deb3937bff7e44c0450c796e1c8e538/globalmount: transport endpoint is not connected
