### ISSUE TITLE
Does s3fs support virtual style?

### ISSUE THREAD

**Issue by ChandlerBent** [yandex-cloud/k8s-csi-s3#116]
yaml
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: harbor-storage-cos
provisioner: ru.yandex.s3.csi
parameters:
  mounter: s3fs
  # you can set mount options here, for example limit memory cache size (recommended)
  options: ""
  # to use an existing bucket, specify it here:
  # bucket: 
  csi.storage.k8s.io/provisioner-secret-name: cos-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: cos-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: cos-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: cos-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
```

cos-s3-secret
```
---
apiVersion: v1
data:
  accessKeyID: xxx
  endpoint: https://xxx.cos.ap-guangzhou.myqcloud.com
  secretAccessKey: xxxx
immutable: false
kind: Secret
metadata:
  name: cos-s3-secret
  namespace: kube-system
  resourceVersion: '25997598'
type: Opaque
```

I got the error by creating pvc
```
ailed to provision volume with StorageClass "storage-cos": rpc error: code = Unknown desc = failed to check if bucket pvc-4344afb4-9f97-4869-83bf-ec629118335f exists: The specified key does not exist.
```
