### ISSUE TITLE
error getting deleter volume plugin for volume "csi-s3-manual": no deletable volume plugin matched

### ISSUE THREAD

**Issue by schlichtanders** [yandex-cloud/k8s-csi-s3#129]
Hi there,

I am having issues with deletion of the manual PV after the respective PVC got deleted (because the pod got deleted).

```yaml
# Statically provisioned PVC:
# An existing bucket or path inside bucket manually created
# by the administrator beforehand will be bound to the PVC,
# and it won't be removed when you remove the PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-s3-manual
  # cluster wide object, no namespace
spec:
  storageClassName: csi-s3
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: mynamespace
    name: csi-s3-manual-pvc
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: ru.yandex.s3.csi
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    volumeAttributes:
      capacity: 10Gi
      mounter: geesefs
      options: --memory-limit 1000 --dir-mode 0777 --file-mode 0666
    volumeHandle: mybucket/mypath
``` 

kubectl describe shows the following Event
```
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  VolumeFailedDelete  37s   persistentvolume-controller  error getting deleter volume plugin for volume "csi-s3-manual": no deletable volume plugin matched
```
