### ISSUE TITLE
volume mounted as root:root despite options are set otherwise

### ISSUE THREAD

**Issue by schlichtanders** [yandex-cloud/k8s-csi-s3#132]
Hello,

If I understood it correctly, then the geesefs csi s3 volume is mounted as root:root because the yandex csi driver is doing it so (and not because another kubernetes controller does this somehow generically for volumes).

But I set `--memory-limit 1000 --dir-mode 0777 --file-mode 0644 --setuid 1000 --setgid 1000` for the options, so why is it still mounted as root?

I get permission denied EACCES errors respectively.

I am using static PV which looks like this:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myname
spec:
  storageClassName: csi-s3
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: myname
    namespace: mynamespace
  csi:
    driver: ru.yandex.s3.csi
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    volumeAttributes:
      capacity: 10Gi
      mounter: geesefs
      options: --memory-limit 1000 --dir-mode 0777 --file-mode 0644 --setuid 1000 --setgid 1000
    volumeHandle: bucket/folder
```

It is mounted, but the permissions are wrong

**Comment by pasztorl** [comment]
Also as I see the directory permission mask option takes no effect since your ls shows the directory permission is 766 but in your options set to 777

**Comment by schlichtanders** [comment]
I recreated everything (maybe there was an old storage class still hanging around) but still get the root/root 

now `ls -l` shows
```
drwxrwxrwx. 2 root       root       4096 Aug 12 08:33 mymount
```

Another issue pointed me to this line in the code
https://github.com/yandex-cloud/k8s-csi-s3/blob/80dcfa4c021f726d67fca3e4df78e2a49a5c3e6b/pkg/mounter/geesefs.go#L97-L101
where it is indeed overwriting the uid and gid args.

**Comment by schlichtanders** [comment]
@pasztorl can you take another look? this really looks like a bug to me.
Such that geesefs is unusable for nonroot users

**Comment by brenodt** [comment]
Unless I'm misinterpreting something, `setuid/gid` are meant to control the geesefs process privileges, so what we are actually looking for are the `uid` and `gid` flags, instead.

On top of that, seems that this only worked to be by also passing `--enable-perms`:
```yaml
// [..]
    volumeAttributes:
      capacity: 5Gi
      mounter: geesefs
      options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666 --uid 1000 --setuid 1000 --gid 1000 --setgid 1000 --enable-perms"
```
