### ISSUE TITLE
Cannot create S3 volume on ceph, having "The provided 'x-amz-content-sha256' header does not match what was computed." error

### ISSUE THREAD

**Issue by zentavr** [yandex-cloud/k8s-csi-s3#139]
I'd created the PVC like:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-db-dump
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 750Gi
  storageClassName: csi-s3
```

The CSI driver is the latest 0.41.1 and installed with the values:
```
---
storageClass:
  # Specifies whether the storage class should be created
  create: true
  singleBucket: "cti-k8s-csi"

secret:
  # Specifies whether the secret should be created
  create: true
  # Name of the secret
  name: "csi-s3-secret"
  # S3 Access Key
  accessKey: "*******redacted*******"
  # S3 Secret Key
  secretKey: "*******redacted*******"
  # Endpoint
  endpoint: "http://rgw-slow-dev01.ti.local:80"
```

There are other volumes from the old deployments which are fine. What could be wrong here?
Events:
Reason: `ExternalProvisioning` (source: `persistentvolume-controller`):
```
Waiting for a volume to be created either by the external provisioner 'ru.yandex.s3.csi' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
```

Reason: `ProvisioningFailed` (source: `ru.yandex.s3.csi_csi-s3-provisioner-0_4d383a87-31f4-42c5-b9c9-58d2c6c41063`)
```
failed to provision volume with StorageClass "csi-s3": rpc error: code = Unknown desc = failed to create prefix pvc-a555057d-22e8-489d-bc7c-86e678f2d83f: The provided 'x-amz-content-sha256' header does not match what was computed.
```
