### ISSUE TITLE
Manual PV name by dynamocally required PVC.

### ISSUE THREAD

**Issue by alexz0nder** [yandex-cloud/k8s-csi-s3#155]
Good day 

Currently, I'm using version 0.42.1 of CSI-S3 Driver Helm Chart to have a Persistent Volume for every user Jupyter POD.
And, according to the [README](https://github.com/yandex-cloud/k8s-csi-s3?tab=readme-ov-file#4-test-the-s3-driver), this driver creates a HASH-named PV for every dynamically requested PVC. So I do have a HASH-named directories located in S3 bucket, which is inconvenient.
NAME                    STATUS   VOLUME                                                                    CAPACITY   ACCESS    MODES   STORAGECL
claim-testuser      Bound      pvc-714f477a-0304-4f21-9aaa-47f17e85968d     150Mi          RWO                          csi-s3

It would be a lot more usable if the PV name template could be passed as well to have every PV created with the same name as PVC.
For example:
NAME                    STATUS   VOLUME                 CAPACITY   ACCESS    MODES   STORAGECL
claim-testuser      Bound      volume-testuser     150Mi          RWO                          csi-s3

**Comment by livingroot** [comment]
You need to create StorageClass, PVC and PersistentVolume by yourself.

Here is example:



```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ru.yandex.s3.csi
  name: *WANTED_PV_NAME*
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: csi-s3-pvc
    namespace: **YOUR_NAMESPACE**
  csi:
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    driver: ru.yandex.s3.csi
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    volumeAttributes:
      bucket: **YOUR_BUCKET_NAME**
      capacity: "10737418240"
      mounter: geesefs
      options: --memory-limit 1000 --dir-mode 0777 --file-mode 0666 --no-systemd --setuid 0
      storage.kubernetes.io/csiProvisionerIdentity: 1734780824694-8081-ru.yandex.s3.csi
    volumeHandle: **YOUR_BUCKET_NAME**/ # Don't forget slash here. You can define your custom folder name here
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-s3-custom
  volumeMode: Filesystem
```

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-s3-custom
parameters:
  bucket: **YOUR_BACKET_NAME**
  csi.storage.k8s.io/controller-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: csi-s3
  csi.storage.k8s.io/node-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: csi-s3
  csi.storage.k8s.io/node-stage-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: csi-s3
  csi.storage.k8s.io/provisioner-secret-name: csi-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: csi-s3
  mounter: geesefs
  options: --memory-limit 1000 --dir-mode 0777 --file-mode 0666 --no-systemd --setuid 0
provisioner: ru.yandex.s3.csi
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
```

And in deployment:

```yaml
      volumes:
        - name: s3-storage
          persistentVolumeClaim:
            claimName: csi-s3-pvc
```

**Comment by livingroot** [comment]
And also provide secrets by yourself:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
type: Opaque
data:
  accessKeyID: 
  endpoint: 
  region: 
  secretAccessKey: 
  ```

**Comment by Chaar132** [comment]
Hello, I have written the YAML file following your steps as shown below: ‌

```
**#PV**
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ch.ctrox.csi.s3-driver
  finalizers:
  - kubernetes.io/pv-protection
  name: gaea
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: csi-vname-pvc
    namespace: default
  csi:
    controllerPublishSecretRef:
      name: minio-s3-secret
      namespace: kube-system
    driver: ch.ctrox.csi.s3-driver
    nodePublishSecretRef:
      name: minio-s3-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: minio-s3-secret
      namespace: kube-system
    volumeAttributes:
      bucket: k8s-test
      mounter: s3fs
      storage.kubernetes.io/csiProvisionerIdentity: 1740450877562-8081-ch.ctrox.csi.s3-driver
    volumeHandle: k8s-test/gaea
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-s3-custom
  volumeMode: Filesystem
```

```
**#PVC**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-vname-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" 

```
```
**#storageclass**
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-s3-custom
parameters:
  bucket: k8s-test
  csi.storage.k8s.io/controller-publish-secret-name: minio-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: minio-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: minio-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: minio-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  mounter: s3fs
provisioner: ch.ctrox.csi.s3-driver
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
```

**#secret**
apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-secret
  namespace: kube-system
type: Opaque
stringData:
  accessKeyID: "xxxxxxx"
  secretAccessKey: "xxxxxxx"
  endpoint: http://xxxxxxx:9000
  bucket: k8s-test 
```


```
**#pod to test**
apiVersion: v1
kind: Pod
metadata:
  name: vname-app
  namespace: default
spec:
  containers:
   - name: csi-s3-test-nginx
     image: nginx
     volumeMounts:
       - mountPath: /data
         name: webroot
  volumes:
   - name: webroot
     persistentVolumeClaim:
       claimName: csi-vname-pvc

```
But ‌when I start the pod, I encounter an error in pod vname-app.

`  Warning  FailedMount             5s (x5 over 13s)  kubelet                  MountVolume.MountDevice failed for volume "gaea" : rpc error: code = Unknown desc = The specified key does not exist.`

 Have I made any mistakes in my code? I look forward to your reply.
