### ISSUE TITLE
Bucket folder fails to unmount when deleting pod

### ISSUE THREAD

**Issue by htmljosh** [yandex-cloud/k8s-csi-s3#45]
Using a manual pvc, when deleting the pod it's mounted on and recreating it, I get this error:

> MountVolume.MountDevice failed for volume "manualbucket-with-path" : kubernetes.io/csi: attacher.MountDevice failed to create dir "/var/lib/kubelet/plugins/kubernetes.io/csi/ru.yandex.s3.csi/5e0c8b151eaa5ff5fba3d9eb96cf3f82d1b7ccc6703ef5c673ca7f59cafff43b/globalmount":  mkdir /var/lib/kubelet/plugins/kubernetes.io/csi/ru.yandex.s3.csi/5e0c8b151eaa5ff5fba3d9eb96cf3f82d1b7ccc6703ef5c673ca7f59cafff43b/globalmount: file exists

I can run a umount on that directory and then rm -rf it but seems like kinda a shoddy solution. I could be missing something simple here!

**Comment by FF7C7** [comment]
Возможно связано. Натолкнулся на похожее поведение в режиме systemd

- Когда pod штатно завершается, запущенному на хосте процессу geesefs отправляется сигнал SIGTERM.

- Geesefs пытается размонтировать globalmount, но из-за того, что процесс на хосте запускается под пользователем [nobody](https://github.com/yandex-cloud/k8s-csi-s3/blob/3b38d545abe3cc9b5b29b451bab24fd9a33771d8/pkg/mounter/geesefs.go#LL91C1-L91C1), у него не хватает прав на это. В логах временного systemd unit это видно как permission denied, после чего по таймауту процесс завершается по SIGKILL и оставляет за собой "мусор", который и не дает запуститься новому поду.

Если я правильно понял общую картину, kubelet создает этот маунтпоинт изначально от своего пользователя (root) с правами 750 https://github.com/kubernetes/kubernetes/blob/041bb9a56cb56ebf4ff9305f435a71c135bfc19c/pkg/volume/csi/csi_attacher.go#L342

Собственно решить это аномальное поведение помогло указание --setuid 0 в storageclass

> options: "--memory-limit 500 --dir-mode 0777 --file-mode 0666 --setuid 0"

После чего все стало корректно размонтироваться при штатном завершении пода

**Comment by jidckii** [comment]
Кажется в какой то версии аргументы переопределения `--setuid` срали захардкожены и их нельзя переопределить

https://github.com/yandex-cloud/k8s-csi-s3/blob/d04af5f89bd8e94af0470ac7af58c25fa4e473fa/pkg/mounter/geesefs.go#L97

**Comment by jidckii** [comment]
## Проблема

И так корень проблемы ошибок типа
```
2024/04/29 13:40:19.070839 main.ERROR Failed to unmount in response to terminated: exec: "fusermount": executable file not found in $PATH
```
Это собственно отсутствие пакета `fuse` на хосте.

## Решение

Есть 2 решения:

1. Не использовать systemd для монтирования, добавьте параметры в описание **StorageClass** или **PV**, если монтируете существуещтй бакет.
подробнее тут: https://github.com/yandex-cloud/k8s-csi-s3?tab=readme-ov-file#geesefs
```
parameters.options: "--no-systemd"
```


2. Установить пакет `fuse` на хост систему. Но если ваш облачный провайдер не даёт кастомизировать образы VM, то это может быть проблемой, так как даже если вы установите пакет, после ротации узлов, пакета снова не будет.

пример как установить `fuse` на все хосты в DO KaaS :

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install-package-script
  namespace: kube-system
data:
  install-package.sh: |
    #!/bin/bash
    set -xe
    # Используем chroot для доступа к файловой системе хоста
    chroot /host /bin/bash <<'EOF'
    apt-get update
    apt-get install -y fuse
    EOF
    sleep infinity

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-package-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: install-package
  template:
    metadata:
      labels:
        name: install-package
    spec:
      hostPID: true
      containers:
      - name: installer
        image: debian:12 # Образ должен совпадать c хост состемой
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
        - name: install-script
          mountPath: /usr/local/bin/install-package.sh
          subPath: install-package.sh
          readOnly: true
        command: ["bash"]
        args: ["/usr/local/bin/install-package.sh"]
      restartPolicy: Always
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: install-script
        configMap:
          name: install-package-script
      tolerations:
      - effect: NoSchedule
        operator: Exists
  updateStrategy:
    type: RollingUpdate

```

`kubectl apply -f app.yaml`
wait 5 min
`kubectl delete -f app.yaml`
