### ISSUE TITLE
Successfully mount with static method but not objects seen inside the container

### ISSUE THREAD

**Issue by leonjyq** [yandex-cloud/k8s-csi-s3#49]
Sorry, I am not sure if I understand correctly, I have successfully followed the example pvc-manual.yaml to create the pod and made it run, But I can't see the object which is existing in the bucket. Can someone help me?

**Comment by leonjyq** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
spec:
  containers:
  - name: app
    image: public.ecr.aws/docker/library/centos:centos7.9.2009
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: csi-s3-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-s3
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-s3
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  # mounter: geesefs
  options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  bucket: sva-map-data
  csi.storage.k8s.io/provisioner-secret-name: csi-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
```
I tried in the dynamic way, I can see the folder has been created in S3 bucket, but no file is uploaded.
![image](https://user-images.githubusercontent.com/5651983/229665099-3602d3d8-d0dd-4d2a-9cc7-4dc1b95820f2.png)
