### ISSUE TITLE
Hardcoded /var/lib/kubelet, no ability to override from Helm

### ISSUE THREAD

**Issue by janpuc** [yandex-cloud/k8s-csi-s3#71]
https://github.com/yandex-cloud/k8s-csi-s3/blob/227e1cf2ddf64e922b45a735059537af9eb31f5d/pkg/mounter/geesefs.go#L147C31-L147C31

When using systemd it defaults pluginDir to /var/lib/kubelet. There is no ability to override this with a Helm Chart.

**Comment by janpuc** [comment]
For people using it as HelmRelease with flux, this postRenderer seems to do the job for now:

```
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: DaemonSet
              name: csi-s3
            patch: |-
              - op: add
                path: "/spec/template/spec/containers/1/env/-"
                value:
                  name: PLUGIN_DIR
                  value: "/var/lib/k0s/kubelet/plugins/ru.yandex.s3.csi"
```
